### ISSUE TITLE
Dock shows up even if mouse isn't above it's area

### ISSUE THREAD

**Issue by Py-GNU-Unix** [fthx/dock-from-dash#13]
If i place the cursor on the bottom of the monitor, even it's far from the dock area, it will show up creating some problems with bottom scrollbars.

https://user-images.githubusercontent.com/78305798/152391586-c5965b55-24e6-4d3b-8d28-b73bf4b22dfe.mp4

I already fixed this in https://github.com/fthx/dock-from-dash/pull/11

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/1ceb8dcb3fb64f68309fb085efc860c29e088243
It's a cleaner way to do that, I think. I did already test this when I created the extension, but I was stuck because the dock's container width is not immediately updated by GS (=> timeout trick)...
Dock's container is roughly  the dock's box (you can check this with LG).

**Comment by fthx** [comment]
Forgot to mention: timeout trick is only useful when you change workareas, eg when you plug a monitor with different resolution. If you stay with 1 screen, there was no issue with dashContainer width update.
