### ISSUE TITLE
Show Dock in full screen applications

### ISSUE THREAD

**Issue by seanleavy** [fthx/dock-from-dash#18]
Hi, just adding a feature request to allow the dock to show when a full screen application is active.

Gnome's default behaviour is to restrict hot corners when a full screen application is active.

An extension called [Fullscreen Hot Corner](https://extensions.gnome.org/extension/1562/fullscreen-hot-corner/) exists to override this behaviour.

The 'meat' of that extension's code is found [here](https://github.com/soal/gnome-shell-fullscreen-hot-corner/blob/master/fullscreen-hot-corner%40sorrow.about.alice.pm.me/extension.js) if you have any interest.

Completely understand if you dont have the time or its too messy or whatever reason.

Rgds :)

EDIT:
grammar

**Comment by fthx** [comment]
Hi,
I'm not sure to do that (games...). I let this open to see if other users request this.
Note it's very easy to do since I included some code to prevent fullscreen dock. You could first try to remove 'if' line 131 and its closing brace line 135. Tell me if you do experience any visual bug.
I could soon introduce some options (through dconf only).

**Comment by fthx** [comment]
I've uploaded this:
https://github.com/fthx/dock-from-dash/commit/8778944447f0e3a3797e3b59e43e687e0879a3a9
Just set the header variable.
