### ISSUE TITLE
Sometimes enter unwanted overview on Thunderbird app icon clik

### ISSUE THREAD

**Issue by fthx** [fthx/dock-from-dash#41]
Just remember here, that's due to this with Thunderbird:
https://bugs.launchpad.net/ubuntu/+source/thunderbird/+bug/1932328

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/7a6d6ec02c6b572d42945cc9dc81b52d79d4a8c1

@underlinejakez

**Comment by fthx** [comment]
Info maybe related?
https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/e4446cd15ce46bcfddcd1e35ac3f0e70cb132991

**Comment by fthx** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/c02ca54943e8ee39356021bbb2c36b39c7f7e4e5

**Comment by fthx** [comment]
I reopen for future removing of our patch to this GS bug in extension itself.

**Comment by Bananaman** [comment]
@fthx This is a correct patch and should NEVER be removed from Dash from Dock. It is not a GNOME Shell bug.

Removing "override-redirect" windows is extremely important. GNOME Shell itself takes care to skip those windows everywhere when it's important to not include secret windows. The purpose of the "override-redirect" flag is "don't window-manage this window, at all".

**Comment by Bananaman** [comment]
After now looking at the GNOME commits you linked to, I can see however that they're working on hiding `override-redirect` windows from various APIs that you are using. So in that case, in the far future when enough people are using the patched GNOME Shell, then you could remove the manual check since the API itself won't return or activate OR windows.
