### ISSUE TITLE
[Request] Trigger dock by pressure

### ISSUE THREAD

**Issue by arthurflor23** [fthx/dock-from-dash#58]
Hi,

There is a functionality in the dash-to-dock to trigger the dock with pressure mechanism. I don't know if it's possible to implement the same mechanism here, but would be really nice. One reason is to avoid the accidental dock's trigger, when put the mouse quickly in the active area.

Anyway, here are some support links:
- [original request](https://github.com/micheleg/dash-to-dock/issues/55)
- [pull request](https://github.com/micheleg/dash-to-dock/pull/74)
- [fix issue](https://github.com/micheleg/dash-to-dock/pull/102)

**Comment by fthx** [comment]
Hi,

Yes that would be good. At the moment, the code is much simpler than pressure.
I won't do that because I have some other project in dev:
https://extensions.gnome.org/extension/5143/dashbar/
(you should try this brand new extension, that does read the GS dash items, the code is much**99 shorter than Dash to Panel, I really like it).

I see this pressure code done in Hot Edge extension. I had a look but I did not spend time on it.
Well, I wait for a PR.
:-))

**Comment by subpop** [comment]
I think increasing the `toggle-delay` setting value would emulate this behavior fairly well. It would certainly reduce the accidental showing of the dock if the cursor doesn't stay in the hit box for too long.

**Comment by fthx** [comment]
I let this one open since I feel this part of the extension could be better.

**Comment by dgsasha** [comment]
> Hi,
> 
> Yes that would be good. At the moment, the code is much simpler than pressure. I won't do that because I have some other project in dev: https://extensions.gnome.org/extension/5143/dashbar/ (you should try this brand new extension, that does read the GS dash items, the code is much**99 shorter than Dash to Panel, I really like it).
> 
> I see this pressure code done in Hot Edge extension. I had a look but I did not spend time on it. Well, I wait for a PR. :-))

I got this feature working, I can open a pull request later today, haven't put it on GitHub yet.

**Comment by fthx** [comment]
That's already done, since GS 45 version
