### ISSUE TITLE
Prevent maximized windows from maximizing under the dock

### ISSUE THREAD

**Issue by subpop** [fthx/dock-from-dash#61]
Apologies if this has been requested before. I searched both open and closed issues and didn't find anything that sounds like this.

Is it possible to augment the "always visible" behavior so that when a window is maximized, it doesn't maximize underneath the dock? I use maximized windows a lot, and having the dock always appear on top of the window content makes it difficult to access the window content that's covered by the dock. Would it be possible to reduce the window's computed maximized height by the height of the dock?

**Comment by fthx** [comment]
Sorry, I won't do that.
I understand your concern, as I did think the same using this option.
If you want usable ext, simply do not use 'always visible' :-) .

ATM, I do use my new extension:
https://extensions.gnome.org/extension/5143/dashbar/

There are no comments but frankly speaking I'm very proud of it, since it's a complete rewrite of BaBar extension with a different logic. It does use a lot of native GS stuff and is very light, not like Dash to Panel. So you willl have your dash always displayed in your panel.
